name: "Shell Commands"
on: [push, pull_request]
jobs: 
    run-python-command:
      runs-on: ubuntu-latest
      steps: 
        - name: "python command"
          run: |
            import platform
            print(platform.processor())
          shell: python
    
    run-ruby-command:
      runs-on: ubuntu-latest
      needs: ['run-python-command']
      steps: 
        - uses: actions/checkout@v2
        - name: Set up Ruby 2.6
          uses: actions/setup-ruby@v1
          with:
            ruby-version: 2.6

    run-shell-command:
      runs-on: ubuntu-latest
      needs: ['run-python-command','run-ruby-command']
      steps: 
        - name: "echo string"
          run: echo "Hello World"
        - name: "multiline script"
          run: |
            node -v
            npm -v
            python -v
    
    run-action:
      runs-on: ubuntu-latest
      steps:
        - name: list files before checkout
          run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
            echo " ${{ github.token }}"
        - name: Taking checkout
          uses: actions/checkout@v1
        - name: list files after checkout
          run: |
            pwd
            ls -a
        - name: Running using external actions
          id: greeting
          uses: actions/hello-world-javascript-action@v1 #here you can use branch, version or commit id
          with: 
            who-to-greet: 'Mona the Octocat'
        - name: Log Greeting Time
          run: echo "time"