name: "Shell Commands"
on: [push]
jobs: 
    run-python-command:
      runs-on: ubuntu-latest
      steps: 
        - name: "python command"
          run: |
            import platform
            print(platform.processor())
          shell: python
    
    run-ruby-command:
      runs-on: ubuntu-latest
      needs: ['run-python-command']
      steps: 
        - uses: actions/checkout@v2
        - name: Set up Ruby 2.6
          uses: actions/setup-ruby@v1
          with:
            ruby-version: 2.6

    run-shell-command:
      runs-on: ubuntu-latest
      needs: ['run-python-command','run-ruby-command']
      steps: 
        - name: "echo string"
          run: echo "Hello World"
        - name: "multiline script"
          run: |
            node -v
            npm -v
            python -v
    run-action:
      runs-on: ubuntu-latest
      steps:
        - name: Running using external actions
          uses: actions/github-actions-hello@v1
          id: greeting
          with: 
            who-to-greet: 'Mona the Octocat'
        - name: Log Greeting Time
          run: "echo ${{ steps.greeting.outputs.time }}"